app.version.sher: 'v0.10b14021501'
app.version.jquery_bundle_version: '{$app.version.sher}'
app.version.sher_bundle_version: '{$app.version.sher}'
app.version.css_bundle_version: '{$app.version.sher}'
